service: pycon-flask-example
plugins:
  - serverless-python-requirements
  - serverless-wsgi
package:
  exclude:
    - node_modules/**
    - venv/**
provider:
  name: aws
  runtime: python3.7
  timeout: 30
  memorySize: 128
  stage: '${opt:stage, ''dev''}'
  region: '${opt:region, ''ap-southeast-2''}'
  deploymentBucket: pycon-example
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 's3:ListBucket'
      Resource: 'arn:aws:s3:::pycon-example'
    - Effect: Allow
      Action:
        - 's3:PutObject'
        - 's3:ListObjects'
        - 's3:GetObject'
      Resource: 'arn:aws:s3:::pycon-example/*'
functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    environment:
      PYCON_EXAMPLE_URL: https://api.chucknorris.io/jokes/random
custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: true
  stage: ${self:provider.stage}
